/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApoioAoClienteRouteImport } from './routes/apoio-ao-cliente'
import { Route as JornadaRouteImport } from './routes/jornada'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as StakeholdersRouteImport } from './routes/stakeholders'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoioAoClienteRoute = ApoioAoClienteRouteImport.update({
  id: '/apoio-ao-cliente',
  path: '/apoio-ao-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const JornadaRoute = JornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const StakeholdersRoute = StakeholdersRouteImport.update({
  id: '/stakeholders',
  path: '/stakeholders',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apoio-ao-cliente': typeof ApoioAoClienteRoute
  '/jornada': typeof JornadaRoute
  '/kanban': typeof KanbanRoute
  '/marketing': typeof MarketingRoute
  '/stakeholders': typeof StakeholdersRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apoio-ao-cliente': typeof ApoioAoClienteRoute
  '/jornada': typeof JornadaRoute
  '/kanban': typeof KanbanRoute
  '/marketing': typeof MarketingRoute
  '/stakeholders': typeof StakeholdersRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apoio-ao-cliente': typeof ApoioAoClienteRoute
  '/jornada': typeof JornadaRoute
  '/kanban': typeof KanbanRoute
  '/marketing': typeof MarketingRoute
  '/stakeholders': typeof StakeholdersRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apoio-ao-cliente'
    | '/jornada'
    | '/kanban'
    | '/marketing'
    | '/stakeholders'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apoio-ao-cliente'
    | '/jornada'
    | '/kanban'
    | '/marketing'
    | '/stakeholders'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/apoio-ao-cliente'
    | '/jornada'
    | '/kanban'
    | '/marketing'
    | '/stakeholders'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApoioAoClienteRoute: typeof ApoioAoClienteRoute
  JornadaRoute: typeof JornadaRoute
  KanbanRoute: typeof KanbanRoute
  MarketingRoute: typeof MarketingRoute
  StakeholdersRoute: typeof StakeholdersRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoio-ao-cliente': {
      id: '/apoio-ao-cliente'
      path: '/apoio-ao-cliente'
      fullPath: '/apoio-ao-cliente'
      preLoaderRoute: typeof ApoioAoClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jornada': {
      id: '/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof JornadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stakeholders': {
      id: '/stakeholders'
      path: '/stakeholders'
      fullPath: '/stakeholders'
      preLoaderRoute: typeof StakeholdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApoioAoClienteRoute: ApoioAoClienteRoute,
  JornadaRoute: JornadaRoute,
  KanbanRoute: KanbanRoute,
  MarketingRoute: MarketingRoute,
  StakeholdersRoute: StakeholdersRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
